'use client';
import React, { useMemo, useRef, useState } from 'react';
import { X, Download, Share2, AlertCircle, Check } from 'lucide-react';
import QRCode from 'qrcode';
import type { UserProfile } from '../UserProvider';
import IdentityCard from '@/components/IdentityCard';
import { buildPublicProfileUrl } from '@/lib/publicProfileUrl';

interface VCardModalProps {
  isOpen: boolean;
  onClose: () => void;
  data: UserProfile | null;
  isProfileComplete: boolean;
}

interface RequiredField {
  key: string;
  label: string;
  present: boolean;
}

function buildRequiredFields(data: UserProfile | null): RequiredField[] {
  const name = data?.fullName || data?.name;
  const role = data?.role === 'Other' ? data?.customRole : data?.role;
  const company = data?.firmName || data?.companyName;
  const place = data?.baseCity || data?.base_city;
  const sectors = data?.sectors || data?.priority_sectors;

  return [
    { key: 'name', label: 'Full Name', present: !!name },
    { key: 'phone', label: 'Contact Number', present: !!data?.phone },
    { key: 'email', label: 'Email', present: !!data?.email },
    { key: 'company', label: 'Company Name', present: !!company },
    { key: 'role', label: 'Profession', present: !!role },
    { key: 'place', label: 'Place', present: !!place },
    { key: 'sectors', label: 'Interested Sector', present: !!(sectors && sectors.length > 0) },
  ];
}

// Escapes text per RFC 6350 (vCard 4.0) — commas, semicolons and backslashes are
// structural delimiters in the format and must be escaped in field values.
export function vcardEscape(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/,/g, '\\,').replace(/;/g, '\\;').replace(/\n/g, '\\n');
}

export function buildVCardText(input: {
  name: string;
  phone: string | null;
  email: string;
  company: string | null;
  role: string | null;
  place: string | null;
  sectors: string[];
}): string {
  const lines = [
    'BEGIN:VCARD',
    'VERSION:3.0',
    `FN:${vcardEscape(input.name)}`,
    `N:${vcardEscape(input.name)};;;;`,
  ];
  if (input.company) lines.push(`ORG:${vcardEscape(input.company)}`);
  if (input.role) lines.push(`TITLE:${vcardEscape(input.role)}`);
  if (input.phone) lines.push(`TEL;TYPE=CELL:${vcardEscape(input.phone)}`);
  lines.push(`EMAIL:${vcardEscape(input.email)}`);
  if (input.place) lines.push(`ADR;TYPE=WORK:;;;${vcardEscape(input.place)};;;`);
  if (input.sectors.length > 0) {
    lines.push(`NOTE:Interested sectors: ${vcardEscape(input.sectors.join(', '))}. Via DealCollab.`);
  }
  lines.push('NOTE:Generated by DealCollab — the AI-driven M&A deal-sourcing platform.');
  lines.push('END:VCARD');
  return lines.join('\r\n');
}

export default function VCardModal({ isOpen, onClose, data, isProfileComplete }: VCardModalProps) {
  const [copyState, setCopyState] = useState<'idle' | 'copied'>('idle');
  const cardRef = useRef<HTMLDivElement>(null);

  const fields = useMemo(() => buildRequiredFields(data), [data]);
  const missing = fields.filter(f => !f.present);
  const canRender = isProfileComplete && missing.length === 0;

  const name = data?.fullName || data?.name || '';
  const role = data?.role === 'Other' ? data?.customRole : data?.role;
  const company = data?.firmName || data?.companyName;
  const place = [data?.baseCity || data?.base_city, data?.baseCountry || data?.base_country].filter(Boolean).join(', ');
  const sectors = data?.sectors || data?.priority_sectors || [];
  const photo = data?.profileImage || data?.profile_image || data?.userAvatar;

  if (!isOpen) return null;

  const vcardText = canRender
    ? buildVCardText({
      name,
      phone: data?.phone || null,
      email: data?.email || '',
      company: company || null,
      role: role || null,
      place: place || null,
      sectors,
    })
    : '';

  const drawCardToCanvas = async (): Promise<HTMLCanvasElement> => {
    const width = 1200;
    const height = 675;
    const canvas = document.createElement('canvas');
    canvas.width = width;
    canvas.height = height;
    const ctx = canvas.getContext('2d');
    if (!ctx) throw new Error('Could not get canvas context');

    // Background gradient (#0B1B2B -> #111827)
    const bgGrad = ctx.createLinearGradient(0, 0, width, height);
    bgGrad.addColorStop(0, '#0B1B2B');
    bgGrad.addColorStop(1, '#111827');
    ctx.fillStyle = bgGrad;
    ctx.fillRect(0, 0, width, height);

    // Decorative ambient glow (#F97316)
    const glowGrad = ctx.createRadialGradient(width - 100, 100, 20, width - 100, 100, 400);
    glowGrad.addColorStop(0, 'rgba(249, 115, 22, 0.25)');
    glowGrad.addColorStop(1, 'rgba(249, 115, 22, 0)');
    ctx.fillStyle = glowGrad;
    ctx.fillRect(0, 0, width, height);

    // Header Badge: DealCollab
    ctx.fillStyle = '#F97316';
    ctx.beginPath();
    ctx.roundRect(70, 60, 44, 44, [10]);
    ctx.fill();

    // Star icon / accent inside badge
    ctx.fillStyle = '#FFFFFF';
    ctx.font = '900 24px sans-serif';
    ctx.textAlign = 'center';
    ctx.textBaseline = 'middle';
    ctx.fillText('✦', 92, 82);

    ctx.textAlign = 'left';
    ctx.font = '900 22px sans-serif';
    ctx.fillStyle = 'rgba(255, 255, 255, 0.85)';
    ctx.fillText('DEALCOLLAB', 128, 83);

    // Profile photo or initial avatar
    const avatarX = 70;
    const avatarY = 140;
    const avatarSize = 130;

    ctx.save();
    ctx.beginPath();
    ctx.roundRect(avatarX, avatarY, avatarSize, avatarSize, [24]);
    ctx.fillStyle = 'rgba(255, 255, 255, 0.08)';
    ctx.fill();
    ctx.lineWidth = 3;
    ctx.strokeStyle = 'rgba(255, 255, 255, 0.15)';
    ctx.stroke();
    ctx.clip();

    let imageDrawn = false;
    if (photo) {
      try {
        const img = new window.Image();
        img.crossOrigin = 'anonymous';
        await new Promise<void>((resolve, reject) => {
          img.onload = () => resolve();
          img.onerror = () => reject();
          img.src = photo;
        });
        ctx.drawImage(img, avatarX, avatarY, avatarSize, avatarSize);
        imageDrawn = true;
      } catch {
        // Fallback to avatar initial
      }
    }

    if (!imageDrawn) {
      ctx.fillStyle = '#F97316';
      ctx.font = '900 56px sans-serif';
      ctx.textAlign = 'center';
      ctx.textBaseline = 'middle';
      ctx.fillText((name[0] || 'D').toUpperCase(), avatarX + avatarSize / 2, avatarY + avatarSize / 2);
    }
    ctx.restore();

    // Name, Role, Firm
    ctx.textAlign = 'left';
    ctx.textBaseline = 'alphabetic';
    ctx.fillStyle = '#FFFFFF';
    ctx.font = '900 42px sans-serif';
    ctx.fillText(name || 'Verified Member', 230, 195);

    if (role) {
      ctx.fillStyle = '#F97316';
      ctx.font = '700 24px sans-serif';
      ctx.fillText(role, 230, 235);
    }

    if (company) {
      ctx.fillStyle = 'rgba(255, 255, 255, 0.65)';
      ctx.font = '600 20px sans-serif';
      ctx.fillText(company, 230, 268);
    }

    // Divider
    ctx.strokeStyle = 'rgba(255, 255, 255, 0.12)';
    ctx.lineWidth = 1.5;
    ctx.beginPath();
    ctx.moveTo(70, 310);
    ctx.lineTo(width - 70, 310);
    ctx.stroke();

    // Contact & Location Grid
    const infoStartY = 360;
    const col1X = 70;
    const col2X = 620;

    // Contact Number
    if (data?.phone) {
      ctx.fillStyle = '#F97316';
      ctx.font = '900 22px sans-serif';
      ctx.fillText('TEL', col1X, infoStartY);
      ctx.fillStyle = '#FFFFFF';
      ctx.font = '600 24px sans-serif';
      ctx.fillText(data.phone, col1X + 65, infoStartY);
    }

    // Email
    if (data?.email) {
      ctx.fillStyle = '#F97316';
      ctx.font = '900 22px sans-serif';
      ctx.fillText('MAIL', col2X, infoStartY);
      ctx.fillStyle = '#FFFFFF';
      ctx.font = '600 24px sans-serif';
      ctx.fillText(data.email, col2X + 75, infoStartY);
    }

    // Location & Organization
    const infoRow2Y = 425;
    if (place) {
      ctx.fillStyle = '#F97316';
      ctx.font = '900 22px sans-serif';
      ctx.fillText('LOC', col1X, infoRow2Y);
      ctx.fillStyle = 'rgba(255, 255, 255, 0.9)';
      ctx.font = '600 24px sans-serif';
      ctx.fillText(place, col1X + 65, infoRow2Y);
    }

    if (company) {
      ctx.fillStyle = '#F97316';
      ctx.font = '900 22px sans-serif';
      ctx.fillText('ORG', col2X, infoRow2Y);
      ctx.fillStyle = 'rgba(255, 255, 255, 0.9)';
      ctx.font = '600 24px sans-serif';
      ctx.fillText(company, col2X + 75, infoRow2Y);
    }

    // Sectors / Focus Chips
    if (sectors.length > 0) {
      let chipX = 70;
      const chipY = 490;
      const chipHeight = 44;

      ctx.font = '700 18px sans-serif';
      for (const s of sectors.slice(0, 4)) {
        const textWidth = ctx.measureText(s).width;
        const chipWidth = textWidth + 36;

        ctx.fillStyle = 'rgba(255, 255, 255, 0.08)';
        ctx.beginPath();
        ctx.roundRect(chipX, chipY, chipWidth, chipHeight, [22]);
        ctx.fill();

        ctx.strokeStyle = 'rgba(255, 255, 255, 0.15)';
        ctx.stroke();

        ctx.fillStyle = '#FFFFFF';
        ctx.textBaseline = 'middle';
        ctx.fillText(s, chipX + 18, chipY + chipHeight / 2);
        chipX += chipWidth + 14;
      }
    }

    // Real, scannable QR code resolving to the public DealCollab profile
    // (never phone/email/internal ids — see src/lib/publicProfileUrl.ts).
    const profileSlug = `usr_${String(data?.id || 'dc').slice(0, 8)}`;
    try {
      const qrSize = 110;
      const qrX = width - 70 - qrSize;
      const qrY = height - 70 - qrSize;
      const qrDataUrl = await QRCode.toDataURL(buildPublicProfileUrl(profileSlug), {
        width: qrSize * 2,
        margin: 1,
        color: { dark: '#000000', light: '#FFFFFF' },
        errorCorrectionLevel: 'M',
      });
      const qrImg = new window.Image();
      await new Promise<void>((resolve, reject) => {
        qrImg.onload = () => resolve();
        qrImg.onerror = () => reject();
        qrImg.src = qrDataUrl;
      });
      ctx.save();
      ctx.beginPath();
      ctx.roundRect(qrX - 8, qrY - 8, qrSize + 16, qrSize + 16, [10]);
      ctx.fillStyle = '#FFFFFF';
      ctx.fill();
      ctx.restore();
      ctx.drawImage(qrImg, qrX, qrY, qrSize, qrSize);
    } catch (err) {
      console.error('Failed to render QR on vCard canvas:', err);
    }

    // Footer Watermark
    ctx.textBaseline = 'alphabetic';
    ctx.textAlign = 'right';
    ctx.font = '600 16px sans-serif';
    ctx.fillStyle = 'rgba(255, 255, 255, 0.4)';
    ctx.fillText('AI-Driven M&A Deal Network · dealcollab.com', width - 70, height - 40);

    return canvas;
  };

  const handleDownloadImage = async (format: 'png' | 'jpeg') => {
    if (!canRender) return;
    try {
      const canvas = await drawCardToCanvas();
      const mimeType = format === 'png' ? 'image/png' : 'image/jpeg';
      const extension = format === 'png' ? 'png' : 'jpg';
      const dataUrl = canvas.toDataURL(mimeType, 0.95);

      const a = document.createElement('a');
      a.href = dataUrl;
      a.download = `${name.replace(/[^a-z0-9]+/gi, '_') || 'dealcollab'}_vcard.${extension}`;
      document.body.appendChild(a);
      a.click();
      a.remove();
    } catch (err) {
      console.error('Failed to download vCard image:', err);
    }
  };

  const handleDownload = () => {
    if (!canRender) return;
    const blob = new Blob([vcardText], { type: 'text/vcard;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${name.replace(/[^a-z0-9]+/gi, '_') || 'dealcollab'}.vcf`;
    document.body.appendChild(a);
    a.click();
    a.remove();
    URL.revokeObjectURL(url);
  };

  const handleShare = async () => {
    if (!canRender) return;
    const shareText = `${name}${role ? ` — ${role}` : ''}${company ? ` @ ${company}` : ''}\nPhone: ${data?.phone}\nEmail: ${data?.email}${place ? `\nBased in: ${place}` : ''}\n\nShared via DealCollab`;
    try {
      // Try Web Share with image if supported
      if (navigator.share && navigator.canShare) {
        try {
          const canvas = await drawCardToCanvas();
          const blob = await new Promise<Blob | null>(res => canvas.toBlob(res, 'image/png'));
          if (blob) {
            const file = new File([blob], `${name.replace(/[^a-z0-9]+/gi, '_') || 'dealcollab'}_vcard.png`, { type: 'image/png' });
            if (navigator.canShare({ files: [file] })) {
              await navigator.share({
                title: `${name} — DealCollab vCard`,
                text: shareText,
                files: [file],
              });
              return;
            }
          }
        } catch {
          // Fall back to text share
        }
      }

      if (navigator.share) {
        await navigator.share({ title: `${name} — DealCollab vCard`, text: shareText });
        return;
      }
      throw new Error('Web Share API unavailable');
    } catch {
      try {
        await navigator.clipboard.writeText(shareText);
        setCopyState('copied');
        setTimeout(() => setCopyState('idle'), 2000);
      } catch {
        // Clipboard unavailable too
      }
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm animate-in fade-in duration-200" onClick={onClose}>
      <div
        className="relative w-full max-w-md bg-white rounded-3xl shadow-2xl border border-gray-100 overflow-hidden flex flex-col max-h-[90vh] animate-in zoom-in-95 duration-200"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="flex items-center justify-between p-5 border-b border-gray-100">
          <h2 className="text-base font-black text-gray-900 tracking-tight">Your vCard</h2>
          <button onClick={onClose} className="w-8 h-8 rounded-full bg-gray-100 hover:bg-gray-200 text-gray-500 hover:text-gray-900 flex items-center justify-center transition-all">
            <X size={16} />
          </button>
        </div>

        <div className="p-5 overflow-y-auto space-y-5">
          {!canRender ? (
            <div className="p-5 rounded-2xl bg-amber-50 border border-amber-200 space-y-3">
              <div className="flex items-center gap-2 text-amber-800 font-bold text-sm">
                <AlertCircle size={16} />
                Complete your profile to activate your vCard
              </div>
              <ul className="space-y-1.5">
                {missing.map(f => (
                  <li key={f.key} className="flex items-center gap-2 text-xs text-amber-700 font-medium">
                    <span className="w-1.5 h-1.5 rounded-full bg-amber-400 shrink-0" />
                    {f.label} is missing
                  </li>
                ))}
              </ul>
              {!isProfileComplete && missing.length === 0 && (
                <p className="text-xs text-amber-700 font-medium">Finish onboarding to unlock your vCard.</p>
              )}
            </div>
          ) : (
            <>
              {/* The DealCollab Public Identity Card */}
              <IdentityCard
                mode="public"
                data={{
                  fullName: name || 'Verified Member',
                  initials: (name ? name.split(' ').map((n: string) => n[0]).slice(0, 2).join('') : 'DC').toUpperCase(),
                  photoUrl: photo || undefined,
                  designation: role || undefined,
                  organisation: company || undefined,
                  headline: data?.expertiseDescription || (data as any)?.headline || undefined,
                  mandateSide: (data?.intent && (data.intent as string[])[0])
                    ? ((data.intent as string[])[0]).replace(/_/g, '-').toLowerCase()
                    : undefined,
                  // Use real profile ticket band if available, otherwise omit
                  ticketBand: (data as any)?.dealSizeMin && (data as any)?.dealSizeMax
                    ? `₹${(data as any).dealSizeMin}–${(data as any).dealSizeMax} Cr`
                    : (data as any)?.ticketBand || undefined,
                  // Use real closed count if available
                  closedCount: (data as any)?.closedCount ?? (data as any)?.closed_count ?? undefined,
                  expertise: data?.expertiseDescription
                    ? [data.expertiseDescription]
                    : (data as any)?.expertise?.length
                      ? (data as any).expertise.slice(0, 3)
                      : undefined,
                  sectors: sectors.slice(0, 4),
                  geographies: (data?.geographies && (data.geographies as string[]).length > 0
                    ? data.geographies as string[]
                    : ['India']).slice(0, 3),
                  phone: data?.phone || undefined,
                  email: data?.email || undefined,
                  location: place || undefined,
                  isVerified: (data as any)?.kycVerified !== undefined ? !!(data as any).kycVerified : true,
                  verifiedCode: String(data?.id || '').slice(-4).toUpperCase() || undefined,
                  profileSlug: `usr_${String(data?.id || 'dc').slice(0, 8)}`,
                }}
                showExportButtons={false}
              />

              {/* Action Buttons: JPG, PNG, VCF, Share */}
              <div className="space-y-2 mt-4">
                <div className="grid grid-cols-2 gap-2.5">
                  <button
                    onClick={() => handleDownloadImage('jpeg')}
                    className="flex items-center justify-center gap-1.5 py-2.5 bg-[#F97316] hover:bg-[#EA580C] text-white rounded-xl text-xs font-bold uppercase tracking-wider transition-all shadow-sm"
                  >
                    <Download size={13} /> Download JPG
                  </button>
                  <button
                    onClick={() => handleDownloadImage('png')}
                    className="flex items-center justify-center gap-1.5 py-2.5 bg-[#1F2937] hover:bg-[#111827] text-white rounded-xl text-xs font-bold uppercase tracking-wider transition-all shadow-sm"
                  >
                    <Download size={13} /> Download PNG
                  </button>
                </div>

                <div className="grid grid-cols-2 gap-2.5">
                  <button
                    onClick={handleDownload}
                    className="flex items-center justify-center gap-1.5 py-2.5 bg-gray-100 hover:bg-gray-200 text-gray-700 rounded-xl text-xs font-bold uppercase tracking-wider transition-all"
                  >
                    <Download size={13} /> vCard (.vcf)
                  </button>
                  <button
                    onClick={handleShare}
                    className="flex items-center justify-center gap-1.5 py-2.5 bg-white border border-gray-200 hover:border-[#F97316] hover:text-[#F97316] text-gray-700 rounded-xl text-xs font-bold uppercase tracking-wider transition-all"
                  >
                    {copyState === 'copied' ? <><Check size={13} /> Copied</> : <><Share2 size={13} /> Share</>}
                  </button>
                </div>
              </div>
            </>
          )}
        </div>
      </div>
    </div>
  );
}
