'use client';
import React, { useMemo, useState } from 'react';
import { X, Download, Share2, AlertCircle, Check } from 'lucide-react';
import QRCode from 'qrcode';
import type { UserProfile } from '../UserProvider';
import DealCollabVCard from './DealCollabVCard';
import { buildPublicProfileUrl } from '@/lib/publicProfileUrl';

export interface ExtendedUserProfile extends UserProfile {
  professionalCategory?: string[] | null;
  userType?: string | null;
  profile_completed?: boolean | null;
  profile_completed_once?: boolean | null;
  headline?: string | null;
  dealSizeMin?: number | string | null;
  dealSizeMax?: number | string | null;
  ticketBand?: string | null;
  closedCount?: number | string | null;
  closed_count?: number | string | null;
  expertise?: string[] | null;
  kycVerified?: boolean | null;
}

interface VCardModalProps {
  isOpen: boolean;
  onClose: () => void;
  data: UserProfile | null;
  isProfileComplete: boolean;
  onEdit?: () => void;
}

interface RequiredField {
  key: string;
  label: string;
  present: boolean;
}

export function isUserBusinessPromoter(data: UserProfile | null): boolean {
  if (!data) return false;
  const profile = data as ExtendedUserProfile;
  const categories = profile.category || profile.professionalCategory || [];
  return (
    (Array.isArray(categories) && categories.includes('Business Owner / Promoter')) ||
    profile.customCategory === 'promoter' ||
    profile.userType === 'promoter' ||
    (!profile.role && !!(profile.companyName || profile.company_name))
  );
}

export function buildRequiredFields(data: UserProfile | null): RequiredField[] {
  const isPromoter = isUserBusinessPromoter(data);
  const name = data?.fullName || data?.name;
  const company = data?.companyName || data?.company_name || data?.firmName || data?.firm_name;

  if (isPromoter) {
    // For Business Promoters, the 3-step profile requires Full Name, Email, and Company Name.
    // Profession defaults to 'Business Promoter', and place/sectors are optional.
    return [
      { key: 'name', label: 'Full Name', present: !!name },
      { key: 'email', label: 'Email', present: !!data?.email },
      { key: 'company', label: 'Company Name', present: !!company },
    ];
  }

  const role = data?.role === 'Other' ? data?.customRole : data?.role;
  const place = data?.baseCity || data?.base_city || data?.baseLocation || data?.base_location;

  return [
    { key: 'name', label: 'Full Name', present: !!name },
    { key: 'email', label: 'Email', present: !!data?.email },
    { key: 'company', label: 'Company Name', present: !!company },
    { key: 'role', label: 'Profession', present: !!role },
    { key: 'place', label: 'Place', present: !!place },
  ];
}

// Escapes text per RFC 6350 (vCard 4.0) — commas, semicolons and backslashes are
// structural delimiters in the format and must be escaped in field values.
export function vcardEscape(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/,/g, '\\,').replace(/;/g, '\\;').replace(/\n/g, '\\n');
}

export function buildVCardText(input: {
  name: string;
  phone: string | null;
  email: string;
  company: string | null;
  role: string | null;
  place: string | null;
  sectors: string[];
}): string {
  const lines = [
    'BEGIN:VCARD',
    'VERSION:3.0',
    `FN:${vcardEscape(input.name)}`,
    `N:${vcardEscape(input.name)};;;;`,
  ];
  if (input.company) lines.push(`ORG:${vcardEscape(input.company)}`);
  if (input.role) lines.push(`TITLE:${vcardEscape(input.role)}`);
  if (input.phone) lines.push(`TEL;TYPE=CELL:${vcardEscape(input.phone)}`);
  lines.push(`EMAIL:${vcardEscape(input.email)}`);
  if (input.place) lines.push(`ADR;TYPE=WORK:;;;${vcardEscape(input.place)};;;`);
  if (input.sectors.length > 0) {
    lines.push(`NOTE:Interested sectors: ${vcardEscape(input.sectors.join(', '))}. Via DealCollab.`);
  }
  lines.push('NOTE:Generated by DealCollab — Connecting People, Possibilities & Deals.');
  lines.push('END:VCARD');
  return lines.join('\r\n');
}

export default function VCardModal({ isOpen, onClose, data, isProfileComplete }: VCardModalProps) {
  const [copyState, setCopyState] = useState<'idle' | 'copied'>('idle');
  const profile = data as ExtendedUserProfile | null;

  const isPromoter = isUserBusinessPromoter(profile);
  const fields = useMemo(() => buildRequiredFields(profile), [profile]);
  const missing = fields.filter(f => !f.present);

  const isProfileActuallyComplete = !!(
    isProfileComplete ||
    profile?.profileCompleted ||
    profile?.profile_completed ||
    profile?.profileCompletedOnce ||
    profile?.profile_completed_once ||
    (profile?.profileCompletion ?? 0) >= 100 ||
    (profile?.profile_completion ?? 0) >= 100
  );

  const name = profile?.fullName || profile?.name || '';
  const canRender = (isProfileActuallyComplete || missing.length === 0) && !!name;

  const role = (profile?.role === 'Other' ? profile?.customRole : profile?.role) ||
    (isPromoter ? 'Business Promoter' : (profile?.customRole || ''));
  const company = profile?.companyName || profile?.company_name || profile?.firmName || profile?.firm_name || '';
  const place = [profile?.baseCity || profile?.base_city, profile?.baseCountry || profile?.base_country].filter(Boolean).join(', ') ||
    (profile?.baseLocation || profile?.base_location || '');
  
  let sectors = profile?.sectors || profile?.priority_sectors || [];
  if (!isPromoter && Array.isArray((profile as unknown as Record<string, unknown>)?.requirements)) {
    const reqSectors = new Set<string>();
    ((profile as unknown as Record<string, unknown>).requirements as Array<{ sectors?: string[] }>).forEach((req) => {
      if (Array.isArray(req.sectors)) {
        req.sectors.forEach((s: string) => reqSectors.add(s));
      }
    });
    if (reqSectors.size > 0) {
      sectors = Array.from(reqSectors);
    }
  }

  const photo = profile?.profileImage || profile?.profile_image || profile?.userAvatar;
  const rawCat = profile?.professionalCategory || profile?.category;
  const categoryText = Array.isArray(rawCat)
    ? rawCat.filter(Boolean).join(', ')
    : rawCat || role || 'Advisor';
  const sectorsText = sectors.length > 0 ? sectors.join(', ') : 'M&A, Growth, Capital';
  const geographiesText = (profile?.geographies && (profile.geographies as string[]).length > 0
    ? (profile.geographies as string[]).join(', ')
    : 'India');
  const basedCityText = place || 'India';
  const profileSlug = `usr_${String(profile?.id || 'dc').slice(0, 8)}`;

  if (!isOpen) return null;

  const vcardText = canRender
    ? buildVCardText({
      name,
      phone: data?.phone || null,
      email: data?.email || '',
      company: company || null,
      role: role || null,
      place: place || null,
      sectors,
    })
    : '';

  const drawCardToCanvas = async (): Promise<HTMLCanvasElement> => {
    const width = 1000;
    const height = 1200;
    const canvas = document.createElement('canvas');
    canvas.width = width;
    canvas.height = height;
    const ctx = canvas.getContext('2d');
    if (!ctx) throw new Error('Could not get canvas context');

    // 1. Crisp white background
    ctx.fillStyle = '#FFFFFF';
    ctx.fillRect(0, 0, width, height);

    // 2. Header: Tagline (left) + Exact DealCollab logo (right, from sample)
    ctx.fillStyle = '#6B7280';
    ctx.font = '500 13px -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif';
    ctx.textAlign = 'left';
    ctx.textBaseline = 'middle';
    ctx.fillText('Connecting People, Possibilities & Deals', 60, 58);

    // DealCollab Logo (exact logo image from sample)
    try {
      const logoImg = new window.Image();
      await new Promise<void>((resolve, reject) => {
        logoImg.onload = () => resolve();
        logoImg.onerror = () => reject();
        logoImg.src = '/dealcollab-logo-2x.png';
      });
      const logoH = 32;
      const logoW = (logoImg.width / logoImg.height) * logoH;
      ctx.drawImage(logoImg, width - 60 - logoW, 58 - logoH / 2, logoW, logoH);
    } catch {
      ctx.textAlign = 'right';
      ctx.font = '900 23px -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif';
      ctx.fillStyle = '#000000';
      ctx.fillText('DealCollab', width - 60, 58);
    }

    // 3. Hero Profile Row
    const photoX = 60;
    const photoY = 105;
    const photoW = 195;
    const photoH = 235;
    const photoRadius = 22;

    // Draw gold border around photo
    ctx.save();
    ctx.beginPath();
    ctx.roundRect(photoX, photoY, photoW, photoH, [photoRadius]);
    ctx.lineWidth = 3.5;
    ctx.strokeStyle = '#E8CF9B';
    ctx.stroke();
    ctx.clip();

    let imageDrawn = false;
    if (photo) {
      try {
        const img = new window.Image();
        img.crossOrigin = 'anonymous';
        await new Promise<void>((resolve, reject) => {
          img.onload = () => resolve();
          img.onerror = () => reject();
          img.src = photo;
        });
        ctx.drawImage(img, photoX, photoY, photoW, photoH);
        imageDrawn = true;
      } catch {
        // Fallback to initials
      }
    }

    if (!imageDrawn) {
      ctx.fillStyle = '#FDF8EE';
      ctx.fillRect(photoX, photoY, photoW, photoH);
      const initials = (name ? name.split(' ').map((n: string) => n[0]).slice(0, 2).join('') : 'DC').toUpperCase();
      ctx.fillStyle = '#B45309';
      ctx.font = 'bold 60px Cambria, Georgia, serif';
      ctx.textAlign = 'center';
      ctx.textBaseline = 'middle';
      ctx.fillText(initials, photoX + photoW / 2, photoY + photoH / 2);
    }
    ctx.restore();

    // Two-Column Info Grid Helper
    const drawWrappedText = (
      text: string,
      x: number,
      startY: number,
      maxWidth: number,
      lineHeight: number,
      maxLines: number = 4
    ): number => {
      const words = text.split(' ');
      let currentLine = '';
      let y = startY;
      let lineCount = 0;

      for (let i = 0; i < words.length; i++) {
        const testLine = currentLine ? `${currentLine} ${words[i]}` : words[i];
        if (ctx.measureText(testLine).width > maxWidth && currentLine) {
          ctx.fillText(currentLine, x, y);
          currentLine = words[i];
          y += lineHeight;
          lineCount++;
          if (lineCount >= maxLines - 1) {
            const rest = words.slice(i).join(' ');
            if (ctx.measureText(rest).width > maxWidth) {
              let trimmed = rest;
              while (trimmed.length > 0 && ctx.measureText(`${trimmed}...`).width > maxWidth) {
                trimmed = trimmed.slice(0, -1);
              }
              currentLine = `${trimmed}...`;
            } else {
              currentLine = rest;
            }
            break;
          }
        } else {
          currentLine = testLine;
        }
      }
      if (currentLine) {
        ctx.fillText(currentLine, x, y);
        y += lineHeight;
      }
      return y;
    };

    // Name, Firm Name, Designation in Cambria Font
    ctx.textAlign = 'left';
    ctx.textBaseline = 'alphabetic';
    const textStartX = 295;
    const heroTextMaxWidth = width - 60 - textStartX;
    let heroTextY = 168;

    // Name in Cambria bold
    ctx.font = 'bold 42px Cambria, Georgia, serif';
    ctx.fillStyle = '#0A0A0A';
    heroTextY = drawWrappedText(name || 'Verified Member', textStartX, heroTextY, heroTextMaxWidth, 48, 2);

    // Firm Name in Cambria
    heroTextY += 16;
    ctx.font = 'bold 22px Cambria, Georgia, serif';
    ctx.fillStyle = '#0A0A0A';
    ctx.fillText('Firm Name: ', textStartX, heroTextY);
    const fnWidth = ctx.measureText('Firm Name: ').width;
    ctx.font = 'normal 22px Cambria, Georgia, serif';
    ctx.fillStyle = '#1F2937';
    heroTextY = drawWrappedText(company || 'Independent', textStartX + fnWidth, heroTextY, heroTextMaxWidth - fnWidth, 28, 2);

    // Designation in Cambria
    heroTextY += 12;
    ctx.font = 'bold 22px Cambria, Georgia, serif';
    ctx.fillStyle = '#0A0A0A';
    ctx.fillText('Designation: ', textStartX, heroTextY);
    const desigWidth = ctx.measureText('Designation: ').width;
    ctx.font = 'normal 22px Cambria, Georgia, serif';
    ctx.fillStyle = '#1F2937';
    heroTextY = drawWrappedText(role || 'Advisor', textStartX + desigWidth, heroTextY, heroTextMaxWidth - desigWidth, 28, 2);

    // 4. Golden Divider 1 — dynamically placed below the taller of photo or hero text
    const div1Y = Math.max(photoY + photoH, heroTextY) + 24;
    ctx.fillStyle = '#E8CF9B';
    ctx.fillRect(60, div1Y, width - 120, 2.5);

    // 5. Two-Column Info Grid — dynamically calculated row pairs to guarantee ZERO overlap
    const col1X = 60;
    const col2X = 520;
    const colWidth = 420;
    let currentRowY = div1Y + 45;

    // Row 1: Contact (left) vs Email (right)
    ctx.font = 'bold 23px Cambria, Georgia, serif';
    ctx.fillStyle = '#0A0A0A';
    ctx.fillText('Contact:', col1X, currentRowY);
    ctx.fillText('Email:', col2X, currentRowY);

    ctx.font = 'normal 21px Cambria, Georgia, serif';
    ctx.fillStyle = '#1F2937';
    const contactBottom = drawWrappedText(data?.phone || 'Not provided', col1X, currentRowY + 32, colWidth, 29, 2);
    const emailBottom = drawWrappedText(data?.email || 'Not provided', col2X, currentRowY + 32, colWidth, 29, 2);

    currentRowY = Math.max(contactBottom, emailBottom) + 26;

    // Row 2: Professional Category (left) vs Based City (right)
    ctx.font = 'bold 23px Cambria, Georgia, serif';
    ctx.fillStyle = '#0A0A0A';
    ctx.fillText('Professional Category', col1X, currentRowY);
    ctx.fillText('Based City:', col2X, currentRowY);

    ctx.font = 'normal 21px Cambria, Georgia, serif';
    ctx.fillStyle = '#1F2937';
    const catBottom = drawWrappedText(categoryText, col1X, currentRowY + 32, colWidth, 29, 4);
    const cityBottom = drawWrappedText(basedCityText, col2X, currentRowY + 32, colWidth, 29, 3);

    currentRowY = Math.max(catBottom, cityBottom) + 26;

    // Row 3: Focus Sector (left) vs Focus Geography (right)
    ctx.font = 'bold 23px Cambria, Georgia, serif';
    ctx.fillStyle = '#0A0A0A';
    ctx.fillText('Focus Sector:', col1X, currentRowY);
    ctx.fillText('Focus Geography:', col2X, currentRowY);

    ctx.font = 'normal 21px Cambria, Georgia, serif';
    ctx.fillStyle = '#1F2937';
    const secBottom = drawWrappedText(sectorsText, col1X, currentRowY + 32, colWidth, 29, 4);
    const geoBottom = drawWrappedText(geographiesText, col2X, currentRowY + 32, colWidth, 29, 4);

    currentRowY = Math.max(secBottom, geoBottom) + 30;

    // 6. Golden Divider 2 — dynamically positioned below the grid
    const div2Y = currentRowY;
    ctx.fillStyle = '#E8CF9B';
    ctx.fillRect(60, div2Y, width - 120, 2.5);

    // 7. Footer: Pitch (left) + QR code (right) in Cambria font
    const footerStartY = div2Y + 36;
    const pitchX = 60;
    const pitchWidth = 660;

    // Pitch headline
    ctx.font = 'bold 18px Cambria, Georgia, serif';
    ctx.fillStyle = '#0A0A0A';
    const pitchHeadBottom = drawWrappedText(
      'Accelerate your next M&A, Joint Venture, Partnership, or Fundraising round.......',
      pitchX,
      footerStartY,
      pitchWidth,
      26,
      2
    );

    // Pitch body
    ctx.font = 'normal 16px Cambria, Georgia, serif';
    ctx.fillStyle = '#1F2937';
    drawWrappedText(
      'DealCollab connects you with the ideal counterparties and unlocks premium deal-sourcing opportunities tailored to your strategic goals.',
      pitchX,
      pitchHeadBottom + 6,
      pitchWidth,
      24,
      3
    );

    // QR Code
    const qrSize = 145;
    const qrX = width - 60 - qrSize;
    const qrY = div2Y + 22;

    try {
      const publicUrl = buildPublicProfileUrl(profileSlug);
      const qrDataUrl = await QRCode.toDataURL(publicUrl, {
        width: qrSize * 2,
        margin: 1,
        color: { dark: '#000000', light: '#FFFFFF' },
        errorCorrectionLevel: 'M',
      });
      const qrImg = new window.Image();
      await new Promise<void>((resolve, reject) => {
        qrImg.onload = () => resolve();
        qrImg.onerror = () => reject();
        qrImg.src = qrDataUrl;
      });
      ctx.drawImage(qrImg, qrX, qrY, qrSize, qrSize);

      // dealcollab.org text under QR in Cambria font
      ctx.font = 'bold 15px Cambria, Georgia, serif';
      ctx.fillStyle = '#4B5563';
      ctx.textAlign = 'center';
      ctx.fillText('dealcollab.org', qrX + qrSize / 2, qrY + qrSize + 22);
    } catch (err) {
      console.error('Failed to render QR code on canvas:', err);
    }

    return canvas;
  };

  const handleDownloadImage = async (format: 'png' | 'jpeg') => {
    if (!canRender) return;
    try {
      const canvas = await drawCardToCanvas();
      const mimeType = format === 'png' ? 'image/png' : 'image/jpeg';
      const extension = format === 'png' ? 'png' : 'jpg';
      const dataUrl = canvas.toDataURL(mimeType, 0.95);

      const a = document.createElement('a');
      a.href = dataUrl;
      a.download = `${name.replace(/[^a-z0-9]+/gi, '_') || 'dealcollab'}_vcard.${extension}`;
      document.body.appendChild(a);
      a.click();
      a.remove();
    } catch (err) {
      console.error('Failed to download vCard image:', err);
    }
  };

  const handleDownload = () => {
    if (!canRender) return;
    const blob = new Blob([vcardText], { type: 'text/vcard;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${name.replace(/[^a-z0-9]+/gi, '_') || 'dealcollab'}.vcf`;
    document.body.appendChild(a);
    a.click();
    a.remove();
    URL.revokeObjectURL(url);
  };

  const handleShare = async () => {
    if (!canRender) return;
    const shareText = `${name}${role ? ` — ${role}` : ''}${company ? ` @ ${company}` : ''}\nPhone: ${data?.phone || ''}\nEmail: ${data?.email || ''}${place ? `\nBased in: ${place}` : ''}\n\nShared via DealCollab`;
    try {
      // Try Web Share with image if supported
      if (navigator.share && navigator.canShare) {
        try {
          const canvas = await drawCardToCanvas();
          const blob = await new Promise<Blob | null>(res => canvas.toBlob(res, 'image/png'));
          if (blob) {
            const file = new File([blob], `${name.replace(/[^a-z0-9]+/gi, '_') || 'dealcollab'}_vcard.png`, { type: 'image/png' });
            if (navigator.canShare({ files: [file] })) {
              await navigator.share({
                title: `${name} — DealCollab vCard`,
                text: shareText,
                files: [file],
              });
              return;
            }
          }
        } catch {
          // Fall back to text share
        }
      }

      if (navigator.share) {
        await navigator.share({ title: `${name} — DealCollab vCard`, text: shareText });
        return;
      }
      throw new Error('Web Share API unavailable');
    } catch {
      try {
        await navigator.clipboard.writeText(shareText);
        setCopyState('copied');
        setTimeout(() => setCopyState('idle'), 2000);
      } catch {
        // Clipboard unavailable too
      }
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-3 sm:p-4 bg-black/60 backdrop-blur-sm animate-in fade-in duration-200" onClick={onClose}>
      <div
        className="relative w-full max-w-lg bg-gray-50 rounded-3xl shadow-2xl border border-gray-200 overflow-hidden flex flex-col max-h-[95vh] animate-in zoom-in-95 duration-200"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="flex items-center justify-between px-5 py-3.5 bg-white border-b border-gray-200 shrink-0">
          <div className="flex items-center gap-2">
            <h2 className="text-base font-black text-gray-900 tracking-tight">Your DealCollab vCard</h2>
            <span className="text-[10px] uppercase font-bold tracking-wider px-2 py-0.5 rounded-full bg-amber-100 text-amber-800">
              Verified
            </span>
          </div>
          <button onClick={onClose} className="w-8 h-8 rounded-full bg-gray-100 hover:bg-gray-200 text-gray-500 hover:text-gray-900 flex items-center justify-center transition-all">
            <X size={16} />
          </button>
        </div>

        <div className="p-4 sm:p-5 overflow-y-auto space-y-4">
          {!canRender ? (
            <div className="p-5 rounded-2xl bg-amber-50 border border-amber-200 space-y-3">
              <div className="flex items-center gap-2 text-amber-800 font-bold text-sm">
                <AlertCircle size={16} />
                Complete your profile to activate your vCard
              </div>
              <ul className="space-y-1.5">
                {missing.map(f => (
                  <li key={f.key} className="flex items-center gap-2 text-xs text-amber-700 font-medium">
                    <span className="w-1.5 h-1.5 rounded-full bg-amber-400 shrink-0" />
                    {f.label} is missing
                  </li>
                ))}
              </ul>
              {!isProfileActuallyComplete && missing.length === 0 && (
                <p className="text-xs text-amber-700 font-medium">Finish onboarding to unlock your vCard.</p>
              )}
            </div>
          ) : (
            <>
              {/* The DealCollab Branded vCard */}
              <DealCollabVCard
                data={{
                  fullName: name || 'Verified Member',
                  initials: (name ? name.split(' ').map((n: string) => n[0]).slice(0, 2).join('') : 'DC').toUpperCase(),
                  firmName: company || 'Independent',
                  companyName: company || 'Independent',
                  designation: role || 'Advisor',
                  role: role || 'Advisor',
                  phone: data?.phone || '',
                  email: data?.email || '',
                  photoUrl: photo || null,
                  professionalCategory: profile?.professionalCategory || profile?.category || role || 'Advisor',
                  sectors: sectors.length > 0 ? sectors : ['M&A', 'Growth', 'Capital'],
                  baseCity: profile?.baseCity || profile?.base_city || profile?.baseLocation || profile?.base_location || 'Pune',
                  baseCountry: profile?.baseCountry || profile?.base_country || 'India',
                  geographies: (profile?.geographies && (profile.geographies as string[]).length > 0
                    ? profile.geographies as string[]
                    : ['India']),
                  profileSlug,
                }}
              />

              {/* Action Buttons */}
              <div className="space-y-2 pt-2 max-w-[450px] mx-auto w-full">
                <div className="grid grid-cols-2 gap-2.5">
                  <button
                    onClick={() => handleDownloadImage('jpeg')}
                    className="flex items-center justify-center gap-1.5 py-2.5 bg-[#FFB800] hover:bg-[#F59E0B] text-black font-extrabold rounded-xl text-xs uppercase tracking-wider transition-all shadow-sm"
                  >
                    <Download size={14} /> Download JPG
                  </button>
                  <button
                    onClick={() => handleDownloadImage('png')}
                    className="flex items-center justify-center gap-1.5 py-2.5 bg-black hover:bg-gray-900 text-white font-bold rounded-xl text-xs uppercase tracking-wider transition-all shadow-sm"
                  >
                    <Download size={14} /> Download PNG
                  </button>
                </div>

                <div className="grid grid-cols-2 gap-2.5">
                  <button
                    onClick={handleDownload}
                    className="flex items-center justify-center gap-1.5 py-2.5 bg-white hover:bg-gray-100 text-gray-800 border border-gray-300 rounded-xl text-xs font-bold uppercase tracking-wider transition-all shadow-2xs"
                  >
                    <Download size={14} /> vCard (.vcf)
                  </button>
                  <button
                    onClick={handleShare}
                    className="flex items-center justify-center gap-1.5 py-2.5 bg-white hover:bg-gray-100 text-gray-800 border border-gray-300 rounded-xl text-xs font-bold uppercase tracking-wider transition-all shadow-2xs"
                  >
                    {copyState === 'copied' ? <><Check size={14} className="text-emerald-600" /> Copied</> : <><Share2 size={14} /> Share</>}
                  </button>
                </div>
              </div>
            </>
          )}
        </div>
      </div>
    </div>
  );
}

