'use client';
import React, { useMemo, useState } from 'react';
import { X, Download, Share2, AlertCircle, Check } from 'lucide-react';
import QRCode from 'qrcode';
import type { UserProfile } from '../UserProvider';
import DealCollabVCard from './DealCollabVCard';
import { buildPublicProfileUrl } from '@/lib/publicProfileUrl';

export interface ExtendedUserProfile extends UserProfile {
  professionalCategory?: string[] | null;
  userType?: string | null;
  profile_completed?: boolean | null;
  profile_completed_once?: boolean | null;
  headline?: string | null;
  dealSizeMin?: number | string | null;
  dealSizeMax?: number | string | null;
  ticketBand?: string | null;
  closedCount?: number | string | null;
  closed_count?: number | string | null;
  expertise?: string[] | null;
  kycVerified?: boolean | null;
}

interface VCardModalProps {
  isOpen: boolean;
  onClose: () => void;
  data: UserProfile | null;
  isProfileComplete: boolean;
  onEdit?: () => void;
}

interface RequiredField {
  key: string;
  label: string;
  present: boolean;
}

export function isUserBusinessPromoter(data: UserProfile | null): boolean {
  if (!data) return false;
  const profile = data as ExtendedUserProfile;
  const categories = profile.category || profile.professionalCategory || [];
  return (
    (Array.isArray(categories) && categories.includes('Business Owner / Promoter')) ||
    profile.customCategory === 'promoter' ||
    profile.userType === 'promoter' ||
    (!profile.role && !!(profile.companyName || profile.company_name))
  );
}

export function buildRequiredFields(data: UserProfile | null): RequiredField[] {
  const isPromoter = isUserBusinessPromoter(data);
  const name = data?.fullName || data?.name;
  const company = data?.companyName || data?.company_name || data?.firmName || data?.firm_name;

  if (isPromoter) {
    // For Business Promoters, the 3-step profile requires Full Name, Email, and Company Name.
    // Profession defaults to 'Business Promoter', and place/sectors are optional.
    return [
      { key: 'name', label: 'Full Name', present: !!name },
      { key: 'email', label: 'Email', present: !!data?.email },
      { key: 'company', label: 'Company Name', present: !!company },
    ];
  }

  const role = data?.role === 'Other' ? data?.customRole : data?.role;
  const place = data?.baseCity || data?.base_city || data?.baseLocation || data?.base_location;

  return [
    { key: 'name', label: 'Full Name', present: !!name },
    { key: 'email', label: 'Email', present: !!data?.email },
    { key: 'company', label: 'Company Name', present: !!company },
    { key: 'role', label: 'Profession', present: !!role },
    { key: 'place', label: 'Place', present: !!place },
  ];
}

// Escapes text per RFC 6350 (vCard 4.0) — commas, semicolons and backslashes are
// structural delimiters in the format and must be escaped in field values.
export function vcardEscape(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/,/g, '\\,').replace(/;/g, '\\;').replace(/\n/g, '\\n');
}

export function buildVCardText(input: {
  name: string;
  phone: string | null;
  email: string;
  company: string | null;
  role: string | null;
  place: string | null;
  sectors: string[];
}): string {
  const lines = [
    'BEGIN:VCARD',
    'VERSION:3.0',
    `FN:${vcardEscape(input.name)}`,
    `N:${vcardEscape(input.name)};;;;`,
  ];
  if (input.company) lines.push(`ORG:${vcardEscape(input.company)}`);
  if (input.role) lines.push(`TITLE:${vcardEscape(input.role)}`);
  if (input.phone) lines.push(`TEL;TYPE=CELL:${vcardEscape(input.phone)}`);
  lines.push(`EMAIL:${vcardEscape(input.email)}`);
  if (input.place) lines.push(`ADR;TYPE=WORK:;;;${vcardEscape(input.place)};;;`);
  if (input.sectors.length > 0) {
    lines.push(`NOTE:Interested sectors: ${vcardEscape(input.sectors.join(', '))}. Via DealCollab.`);
  }
  lines.push('NOTE:Generated by DealCollab — Connecting People, Possibilities & Deals.');
  lines.push('END:VCARD');
  return lines.join('\r\n');
}

export default function VCardModal({ isOpen, onClose, data, isProfileComplete }: VCardModalProps) {
  const [copyState, setCopyState] = useState<'idle' | 'copied'>('idle');
  const profile = data as ExtendedUserProfile | null;

  const isPromoter = isUserBusinessPromoter(profile);
  const fields = useMemo(() => buildRequiredFields(profile), [profile]);
  const missing = fields.filter(f => !f.present);

  const isProfileActuallyComplete = !!(
    isProfileComplete ||
    profile?.profileCompleted ||
    profile?.profile_completed ||
    profile?.profileCompletedOnce ||
    profile?.profile_completed_once ||
    (profile?.profileCompletion ?? 0) >= 100 ||
    (profile?.profile_completion ?? 0) >= 100
  );

  const name = profile?.fullName || profile?.name || '';
  const canRender = (isProfileActuallyComplete || missing.length === 0) && !!name;

  const role = (profile?.role === 'Other' ? profile?.customRole : profile?.role) ||
    (isPromoter ? 'Business Promoter' : (profile?.customRole || ''));
  const company = profile?.companyName || profile?.company_name || profile?.firmName || profile?.firm_name || '';
  const place = [profile?.baseCity || profile?.base_city, profile?.baseCountry || profile?.base_country].filter(Boolean).join(', ') ||
    (profile?.baseLocation || profile?.base_location || '');
  
  let sectors = profile?.sectors || profile?.priority_sectors || [];
  if (!isPromoter && Array.isArray((profile as unknown as Record<string, unknown>)?.requirements)) {
    const reqSectors = new Set<string>();
    ((profile as unknown as Record<string, unknown>).requirements as Array<{ sectors?: string[] }>).forEach((req) => {
      if (Array.isArray(req.sectors)) {
        req.sectors.forEach((s: string) => reqSectors.add(s));
      }
    });
    if (reqSectors.size > 0) {
      sectors = Array.from(reqSectors);
    }
  }

  const photo = profile?.profileImage || profile?.profile_image || profile?.userAvatar;
  const rawCat = profile?.professionalCategory || profile?.category;
  const categoryText = Array.isArray(rawCat)
    ? rawCat.filter(Boolean).join(', ')
    : rawCat || role || 'Advisor';
  const sectorsText = sectors.length > 0 ? sectors.join(', ') : 'M&A, Growth, Capital';
  const geographiesText = (profile?.geographies && (profile.geographies as string[]).length > 0
    ? (profile.geographies as string[]).join(', ')
    : 'India');
  const basedCityText = place || 'India';
  const profileSlug = `usr_${String(profile?.id || 'dc').slice(0, 8)}`;

  if (!isOpen) return null;

  const vcardText = canRender
    ? buildVCardText({
      name,
      phone: data?.phone || null,
      email: data?.email || '',
      company: company || null,
      role: role || null,
      place: place || null,
      sectors,
    })
    : '';

  const drawCardToCanvas = async (): Promise<HTMLCanvasElement> => {
    const width = 868;
    const height = 1024;
    const canvas = document.createElement('canvas');
    canvas.width = width;
    canvas.height = height;
    const ctx = canvas.getContext('2d');
    if (!ctx) throw new Error('Could not get canvas context');

    // 1. Crisp white background
    ctx.fillStyle = '#FFFFFF';
    ctx.fillRect(0, 0, width, height);

    // 2. Header: Tagline on Left (24, 60) + DealCollab Logo on Right (643, 27)
    ctx.fillStyle = '#111827';
    ctx.font = 'bold 16px Cambria, Georgia, serif';
    ctx.textAlign = 'left';
    ctx.textBaseline = 'alphabetic';
    ctx.fillText('Connecting People, Possibilities & Deals', 24, 60);

    try {
      const logoImg = new window.Image();
      await new Promise<void>((resolve, reject) => {
        logoImg.onload = () => resolve();
        logoImg.onerror = () => reject();
        logoImg.src = '/dealcollab-logo.png';
      });
      ctx.drawImage(logoImg, 643, 27, 192, 50);
    } catch {
      ctx.textAlign = 'right';
      ctx.font = '900 24px -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif';
      ctx.fillStyle = '#000000';
      ctx.fillText('DealCollab', 844, 52);
    }

    // Helper for wrapped text
    const drawWrappedText = (
      text: string,
      x: number,
      startY: number,
      maxWidth: number,
      lineHeight: number,
      maxLines: number = 4
    ): number => {
      ctx.textAlign = 'left';
      ctx.textBaseline = 'alphabetic';
      const words = String(text || '').split(' ');
      let currentLine = '';
      let y = startY;
      let lineCount = 0;

      for (let i = 0; i < words.length; i++) {
        const testLine = currentLine ? `${currentLine} ${words[i]}` : words[i];
        if (ctx.measureText(testLine).width > maxWidth && currentLine) {
          ctx.fillText(currentLine, x, y);
          currentLine = words[i];
          y += lineHeight;
          lineCount++;
          if (lineCount >= maxLines - 1) {
            const rest = words.slice(i).join(' ');
            if (ctx.measureText(rest).width > maxWidth) {
              let trimmed = rest;
              while (trimmed.length > 0 && ctx.measureText(`${trimmed}...`).width > maxWidth) {
                trimmed = trimmed.slice(0, -1);
              }
              currentLine = `${trimmed}...`;
            } else {
              currentLine = rest;
            }
            break;
          }
        } else {
          currentLine = testLine;
        }
      }
      if (currentLine) {
        ctx.fillText(currentLine, x, y);
        y += lineHeight;
      }
      return y;
    };

    // 3. Hero Profile Row: Square 259 x 259 photo at (34, 114) with protected golden frame & 10px inner padding
    const photoX = 34;
    const photoY = 114;
    const photoW = 259;
    const photoH = 259;
    const photoRadius = 24;
    const photoPadding = 10;

    // Outer white box fill
    ctx.save();
    ctx.beginPath();
    ctx.roundRect(photoX, photoY, photoW, photoH, [photoRadius]);
    ctx.fillStyle = '#FFFFFF';
    ctx.fill();

    // Inner photo area with rounded corners
    const innerX = photoX + photoPadding;
    const innerY = photoY + photoPadding;
    const innerW = photoW - photoPadding * 2;
    const innerH = photoH - photoPadding * 2;
    const innerRadius = 16;

    let imageDrawn = false;
    if (photo) {
      try {
        const img = new window.Image();
        img.crossOrigin = 'anonymous';
        await new Promise<void>((resolve, reject) => {
          img.onload = () => resolve();
          img.onerror = () => reject();
          img.src = photo;
        });

        ctx.save();
        ctx.beginPath();
        ctx.roundRect(innerX, innerY, innerW, innerH, [innerRadius]);
        ctx.clip();

        // Scale & crop properly: if portrait, bias towards upper portion where face is located
        const scale = Math.max(innerW / img.width, innerH / img.height);
        const sw = innerW / scale;
        const sh = innerH / scale;
        const sx = (img.width - sw) / 2;
        const sy = img.height > img.width ? Math.max(0, (img.height - sh) * 0.2) : (img.height - sh) / 2;

        ctx.drawImage(img, sx, sy, sw, sh, innerX, innerY, innerW, innerH);
        ctx.restore();
        imageDrawn = true;
      } catch {
        // Fallback to initials
      }
    }

    if (!imageDrawn) {
      ctx.save();
      ctx.beginPath();
      ctx.roundRect(innerX, innerY, innerW, innerH, [innerRadius]);
      ctx.fillStyle = '#FDF8EE';
      ctx.fill();
      const initials = (name ? name.split(' ').map((n: string) => n[0]).slice(0, 2).join('') : 'DC').toUpperCase();
      ctx.fillStyle = '#B45309';
      ctx.font = 'bold 64px Cambria, Georgia, serif';
      ctx.textAlign = 'center';
      ctx.textBaseline = 'middle';
      ctx.fillText(initials, innerX + innerW / 2, innerY + innerH / 2);
      ctx.restore();
    }

    // Outer Golden Border drawn cleanly ON TOP so it is NEVER covered or removed
    ctx.beginPath();
    ctx.roundRect(photoX, photoY, photoW, photoH, [photoRadius]);
    ctx.lineWidth = 3.5;
    ctx.strokeStyle = '#EFD2A5';
    ctx.stroke();
    ctx.restore();

    // Name, Firm Name, Designation
    const textStartX = 312;
    const heroTextMaxWidth = width - 24 - textStartX;

    // Name (bold 52px Cambria)
    ctx.textAlign = 'left';
    ctx.textBaseline = 'alphabetic';
    ctx.font = 'bold 52px Cambria, Georgia, serif';
    ctx.fillStyle = '#000000';
    drawWrappedText(name || 'Verified Member', textStartX, 205, heroTextMaxWidth, 56, 2);

    // Firm Name (bold 24px label + normal 24px value)
    let heroY = 264;
    ctx.font = 'bold 24px Cambria, Georgia, serif';
    ctx.fillStyle = '#000000';
    ctx.fillText('Firm Name: ', textStartX, heroY);
    const fnW = ctx.measureText('Firm Name: ').width;
    ctx.font = 'normal 24px Cambria, Georgia, serif';
    ctx.fillStyle = '#1F2937';
    drawWrappedText(company || 'Independent', textStartX + fnW, heroY, heroTextMaxWidth - fnW, 30, 2);

    // Designation (bold 24px label + normal 24px value)
    heroY = 312;
    ctx.font = 'bold 24px Cambria, Georgia, serif';
    ctx.fillStyle = '#000000';
    ctx.fillText('Designation: ', textStartX, heroY);
    const desigW = ctx.measureText('Designation: ').width;
    ctx.font = 'normal 24px Cambria, Georgia, serif';
    ctx.fillStyle = '#1F2937';
    drawWrappedText(role || 'Advisor', textStartX + desigW, heroY, heroTextMaxWidth - desigW, 30, 2);

    // 4. Golden Divider 1
    ctx.fillStyle = '#EFD2A5';
    ctx.fillRect(24, 407, 820, 2.5);

    // 5. Two-Column Info Grid
    const col1X = 60;
    const col2X = 485;
    const colWidth = 360;

    // Row 1: Contact | Email
    const r1HeaderY = 458;
    ctx.font = 'bold 24px Cambria, Georgia, serif';
    ctx.fillStyle = '#000000';
    ctx.fillText('Contact:', col1X, r1HeaderY);
    ctx.fillText('Email:', col2X, r1HeaderY);

    ctx.font = 'normal 24px Cambria, Georgia, serif';
    ctx.fillStyle = '#1F2937';
    const contactBottom = drawWrappedText(data?.phone || 'Not provided', col1X, r1HeaderY + 32, colWidth, 30, 2);
    const emailBottom = drawWrappedText(data?.email || 'Not provided', col2X, r1HeaderY + 32, colWidth, 30, 2);

    // Row 2: Professional Category | Based City (minimum Y: 560 to prevent empty void)
    const r2HeaderY = Math.max(contactBottom, emailBottom, 520) + 40;
    ctx.font = 'bold 24px Cambria, Georgia, serif';
    ctx.fillStyle = '#000000';
    ctx.fillText('Professional Category', col1X, r2HeaderY);
    ctx.fillText('Based City:', col2X, r2HeaderY);

    ctx.font = 'normal 24px Cambria, Georgia, serif';
    ctx.fillStyle = '#1F2937';
    const catBottom = drawWrappedText(categoryText, col1X, r2HeaderY + 32, colWidth, 30, 4);
    const cityBottom = drawWrappedText(basedCityText, col2X, r2HeaderY + 32, colWidth, 30, 3);

    // Row 3: Focus Sector | Focus Geography (minimum Y: 708)
    const r3HeaderY = Math.max(catBottom, cityBottom, 670) + 38;
    ctx.font = 'bold 24px Cambria, Georgia, serif';
    ctx.fillStyle = '#000000';
    ctx.fillText('Focus Sector:', col1X, r3HeaderY);
    ctx.fillText('Focus Geography:', col2X, r3HeaderY);

    ctx.font = 'normal 24px Cambria, Georgia, serif';
    ctx.fillStyle = '#1F2937';
    drawWrappedText(sectorsText, col1X, r3HeaderY + 32, colWidth, 30, 4);
    drawWrappedText(geographiesText, col2X, r3HeaderY + 32, colWidth, 30, 4);

    // 6. Golden Divider 2
    ctx.fillStyle = '#EFD2A5';
    ctx.fillRect(24, 830, 820, 2.5);

    // 7. Footer: Pitch (left) + QR code (right)
    const pitchX = 39;

    // Pitch headline (bold 20px Cambria across 2 lines)
    ctx.font = 'bold 20px Cambria, Georgia, serif';
    ctx.fillStyle = '#000000';
    ctx.fillText('Accelerate your next M&A, Joint Venture, Partnership, or Fundraising', pitchX, 878);
    ctx.fillText('round.......', pitchX, 904);

    // Pitch body (bold 19px "DealCollab" + normal 19px body across 2 lines)
    ctx.font = 'bold 19px Cambria, Georgia, serif';
    ctx.fillStyle = '#000000';
    ctx.fillText('DealCollab ', pitchX, 932);
    const dcW = ctx.measureText('DealCollab ').width;

    ctx.font = 'normal 19px Cambria, Georgia, serif';
    ctx.fillStyle = '#1F2937';
    ctx.fillText('connects you with the ideal counterparties and unlocks premium', pitchX + dcW, 932);
    ctx.fillText('deal-sourcing opportunities tailored to your strategic goals.', pitchX, 958);

    // QR Code
    const qrSize = 118;
    const qrX = 716;
    const qrY = 852;

    try {
      const publicUrl = buildPublicProfileUrl(profileSlug);
      const qrDataUrl = await QRCode.toDataURL(publicUrl, {
        width: qrSize * 2,
        margin: 1,
        color: { dark: '#000000', light: '#FFFFFF' },
        errorCorrectionLevel: 'M',
      });
      const qrImg = new window.Image();
      await new Promise<void>((resolve, reject) => {
        qrImg.onload = () => resolve();
        qrImg.onerror = () => reject();
        qrImg.src = qrDataUrl;
      });
      ctx.drawImage(qrImg, qrX, qrY, qrSize, qrSize);

      // dealcollab.org text under QR in Cambria font
      ctx.font = 'bold 14px Cambria, Georgia, serif';
      ctx.fillStyle = '#4B5563';
      ctx.textAlign = 'center';
      ctx.fillText('dealcollab.org', qrX + qrSize / 2, 992);
    } catch (err) {
      console.error('Failed to render QR code on canvas:', err);
    }

    // 8. Bottom Golden Divider 3
    ctx.fillStyle = '#EFD2A5';
    ctx.fillRect(24, 1010, 820, 3.5);

    return canvas;
  };

  const handleDownloadImage = async (format: 'png' | 'jpeg') => {
    if (!canRender) return;
    try {
      const canvas = await drawCardToCanvas();
      const mimeType = format === 'png' ? 'image/png' : 'image/jpeg';
      const extension = format === 'png' ? 'png' : 'jpg';
      const dataUrl = canvas.toDataURL(mimeType, 0.95);

      const a = document.createElement('a');
      a.href = dataUrl;
      a.download = `${name.replace(/[^a-z0-9]+/gi, '_') || 'dealcollab'}_vcard.${extension}`;
      document.body.appendChild(a);
      a.click();
      a.remove();
    } catch (err) {
      console.error('Failed to download vCard image:', err);
    }
  };

  const handleDownload = () => {
    if (!canRender) return;
    const blob = new Blob([vcardText], { type: 'text/vcard;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${name.replace(/[^a-z0-9]+/gi, '_') || 'dealcollab'}.vcf`;
    document.body.appendChild(a);
    a.click();
    a.remove();
    URL.revokeObjectURL(url);
  };

  const handleShare = async () => {
    if (!canRender) return;
    const shareText = `${name}${role ? ` — ${role}` : ''}${company ? ` @ ${company}` : ''}\nPhone: ${data?.phone || ''}\nEmail: ${data?.email || ''}${place ? `\nBased in: ${place}` : ''}\n\nShared via DealCollab`;
    try {
      // Try Web Share with image if supported
      if (navigator.share && navigator.canShare) {
        try {
          const canvas = await drawCardToCanvas();
          const blob = await new Promise<Blob | null>(res => canvas.toBlob(res, 'image/png'));
          if (blob) {
            const file = new File([blob], `${name.replace(/[^a-z0-9]+/gi, '_') || 'dealcollab'}_vcard.png`, { type: 'image/png' });
            if (navigator.canShare({ files: [file] })) {
              await navigator.share({
                title: `${name} — DealCollab vCard`,
                text: shareText,
                files: [file],
              });
              return;
            }
          }
        } catch {
          // Fall back to text share
        }
      }

      if (navigator.share) {
        await navigator.share({ title: `${name} — DealCollab vCard`, text: shareText });
        return;
      }
      throw new Error('Web Share API unavailable');
    } catch {
      try {
        await navigator.clipboard.writeText(shareText);
        setCopyState('copied');
        setTimeout(() => setCopyState('idle'), 2000);
      } catch {
        // Clipboard unavailable too
      }
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-3 sm:p-4 bg-black/60 backdrop-blur-sm animate-in fade-in duration-200" onClick={onClose}>
      <div
        className="relative w-full max-w-lg bg-gray-50 rounded-3xl shadow-2xl border border-gray-200 overflow-hidden flex flex-col max-h-[95vh] animate-in zoom-in-95 duration-200"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="flex items-center justify-between px-5 py-3.5 bg-white border-b border-gray-200 shrink-0">
          <div className="flex items-center gap-2">
            <h2 className="text-base font-black text-gray-900 tracking-tight">Your DealCollab vCard</h2>
            <span className="text-[10px] uppercase font-bold tracking-wider px-2 py-0.5 rounded-full bg-amber-100 text-amber-800">
              Verified
            </span>
          </div>
          <button onClick={onClose} className="w-8 h-8 rounded-full bg-gray-100 hover:bg-gray-200 text-gray-500 hover:text-gray-900 flex items-center justify-center transition-all">
            <X size={16} />
          </button>
        </div>

        <div className="p-4 sm:p-5 overflow-y-auto space-y-4">
          {!canRender ? (
            <div className="p-5 rounded-2xl bg-amber-50 border border-amber-200 space-y-3">
              <div className="flex items-center gap-2 text-amber-800 font-bold text-sm">
                <AlertCircle size={16} />
                Complete your profile to activate your vCard
              </div>
              <ul className="space-y-1.5">
                {missing.map(f => (
                  <li key={f.key} className="flex items-center gap-2 text-xs text-amber-700 font-medium">
                    <span className="w-1.5 h-1.5 rounded-full bg-amber-400 shrink-0" />
                    {f.label} is missing
                  </li>
                ))}
              </ul>
              {!isProfileActuallyComplete && missing.length === 0 && (
                <p className="text-xs text-amber-700 font-medium">Finish onboarding to unlock your vCard.</p>
              )}
            </div>
          ) : (
            <>
              {/* The DealCollab Branded vCard */}
              <DealCollabVCard
                data={{
                  fullName: name || 'Verified Member',
                  initials: (name ? name.split(' ').map((n: string) => n[0]).slice(0, 2).join('') : 'DC').toUpperCase(),
                  firmName: company || 'Independent',
                  companyName: company || 'Independent',
                  designation: role || 'Advisor',
                  role: role || 'Advisor',
                  phone: data?.phone || '',
                  email: data?.email || '',
                  photoUrl: photo || null,
                  professionalCategory: profile?.professionalCategory || profile?.category || role || 'Advisor',
                  sectors: sectors.length > 0 ? sectors : ['M&A', 'Growth', 'Capital'],
                  baseCity: profile?.baseCity || profile?.base_city || profile?.baseLocation || profile?.base_location || 'Pune',
                  baseCountry: profile?.baseCountry || profile?.base_country || 'India',
                  geographies: (profile?.geographies && (profile.geographies as string[]).length > 0
                    ? profile.geographies as string[]
                    : ['India']),
                  profileSlug,
                }}
              />

              {/* Action Buttons */}
              <div className="space-y-2 pt-2 max-w-[450px] mx-auto w-full">
                <div className="grid grid-cols-2 gap-2.5">
                  <button
                    onClick={() => handleDownloadImage('jpeg')}
                    className="flex items-center justify-center gap-1.5 py-2.5 bg-[#FFB800] hover:bg-[#F59E0B] text-black font-extrabold rounded-xl text-xs uppercase tracking-wider transition-all shadow-sm"
                  >
                    <Download size={14} /> Download JPG
                  </button>
                  <button
                    onClick={() => handleDownloadImage('png')}
                    className="flex items-center justify-center gap-1.5 py-2.5 bg-black hover:bg-gray-900 text-white font-bold rounded-xl text-xs uppercase tracking-wider transition-all shadow-sm"
                  >
                    <Download size={14} /> Download PNG
                  </button>
                </div>

                <div className="grid grid-cols-2 gap-2.5">
                  <button
                    onClick={handleDownload}
                    className="flex items-center justify-center gap-1.5 py-2.5 bg-white hover:bg-gray-100 text-gray-800 border border-gray-300 rounded-xl text-xs font-bold uppercase tracking-wider transition-all shadow-2xs"
                  >
                    <Download size={14} /> vCard (.vcf)
                  </button>
                  <button
                    onClick={handleShare}
                    className="flex items-center justify-center gap-1.5 py-2.5 bg-white hover:bg-gray-100 text-gray-800 border border-gray-300 rounded-xl text-xs font-bold uppercase tracking-wider transition-all shadow-2xs"
                  >
                    {copyState === 'copied' ? <><Check size={14} className="text-emerald-600" /> Copied</> : <><Share2 size={14} /> Share</>}
                  </button>
                </div>
              </div>
            </>
          )}
        </div>
      </div>
    </div>
  );
}

